# Config file for Sphinx build on ReadTheDocs:
# https://docs.readthedocs.io/en/stable/config-file/
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
   install:
      - method: pip
        path: .
        extra_requirements:
          - datastore
      - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
