# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python
#
# gcloud -q app deploy --project arroba-pds app.yaml

# application: arroba-pds

env: flex
runtime: python
runtime_config:
    operating_system: ubuntu18
    runtime_version: 3.12

# need only one instance so that new events can be delivered to subscribeRepos
# subscribers in memory
manual_scaling:
  instances: 1

# https://cloud.google.com/appengine/docs/flexible/python/runtime#application_startup
# https://docs.gunicorn.org/en/latest/settings.html#timeout
# TODO: try asyncio w/eventlet workers
entrypoint: gunicorn --workers 1 --threads 20 -b :$PORT app:app
