# https://packaging.python.org/en/latest/tutorials/packaging-projects/

[build-system]
requires = ['setuptools>=68.0']
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
include = ['arroba*']

# https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data
[tool.setuptools.package-data]
'*' = ['tests/*']

[project.urls]
Homepage = 'https://github.com/snarfed/arroba'
Documentation = 'https://arroba.readthedocs.io/'

[project]
name = 'arroba'
version = '3.0'
authors = [
    { name='Ryan Barrett', email='arroba@ryanb.org' },
]
description = "Python implementation of Bluesky PDS and AT Protocol, including repo, MST, and sync methods"
readme = 'README.md'
license = 'CC0-1.0'
requires-python = '>=3.9'
keywords = ['arroba', 'AT Protocol', 'ATP', 'Bluesky']
classifiers = [
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Operating System :: OS Independent',
    'Intended Audience :: Developers',
    'Development Status :: 3 - Alpha',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

dependencies = [
    'cachetools>=5.0',
    'carbox>=0.3',
    'cryptography>=45.0.0',
    'dag-cbor>=0.3',
    'dag-json>=0.2',
    'dnspython>=2.0.0',
    'lexrpc>=0.8',
    'libipld>=3.0.0',
    'multiformats>=0.3.1',
    'pyjwt>=2.0.0',
    'pymediainfo>=6.0.0',
    'pywebutil>=2.0',
    'requests>=2.0',
    'requests-hardened>=1.0',
]

[project.optional-dependencies]
datastore = [
    'google-cloud-ndb>=2.0',
    'pymemcache>=3.0.0',
]
flask = [
    'Flask>=2.0',
    'werkzeug>=2.3',
]
docs = [
    'sphinx>=7.0.0',
    'sphinx-rtd-theme>=3.0.0',
]
tests = [
    'hypothesis>=6.0',
]

[tool.uv.sources]
arroba =            { editable = true, path = "../arroba" }
brevity =           { editable = true, path = "../brevity" }
carbox =            { editable = true, path = "../carbox" }
flask-gae-static =  { editable = true, path = "../flask-gae-static" }
lexrpc =            { editable = true, path = "../lexrpc" }
mf2util =           { editable = true, path = "../mf2util" }
oauth-dropins =     { editable = true, path = "../oauth-dropins" }
pywebutil =         { editable = true, path = "../webutil" }
secp256k1 =         { editable = true, path = "../secp256k1-py" }

[tool.uv.pip]
# this is in ~/.config/uv/uv.toml

[tool.deptry]
extend_exclude = ['build', 'dist', 'docs', 'mst-test-suite', 'scripts']

[tool.deptry.per_rule_ignores]
# docs-only build tools, not imported in the codebase
DEP002 = [
    'sphinx',
    'sphinx-rtd-theme',
]
